### PR TITLE
feat: s3 upload and cluster scripts

### PR DESCRIPTION
**Pull request by carshadi**
This PR adds 2 major features: 
1) A module for uploading data to s3
2) A system for submitting arbitrary jobs to a cluster, heavily inspired by (read: copied from) https://github.com/JaneliaSciComp/spark-janelia, but in this case we use https://jobqueue.dask.org/ instead of Spark.

Sorry for the monolith, this should have been 2 separate PRs but I got carried away.

For an example cluster job, see https://github.com/AllenNeuralDynamics/nd-data-transfer/blob/feat-s3-upload/scripts/README.md

## Benchmarks
I uploaded a directory of `2,758` tiff slices from the Isilon using 32 HPC cores (split across 4 nodes, 8 tasks per node, 1 cpu-per-task)
```369,103,409,262``` bytes uploaded in ```123.6s```, or `2.986 GB/s`
Command used:
```shell
python cluster/submit.py generate-and-launch-run \
--job_cmd="python s3_upload.py --input /allen/scratch/aindtemp/data/anatomy/exm-hemi-brain/fused_tiffs --bucket fake-bucket --s3_path=upload-test/fused_tiffs --part_size=256000000 --batch_num=10 --cluster --recursive" \
--conda_activate=/allen/programs/aind/workgroups/msma/cameron.arshadi/miniconda3/bin/activate \
--conda_env=nd-data-transfer \
--queue=aind \
--mail_user=cameron.arshadi@alleninstitute.org \
--ntasks_per_node=8 \
--nodes=4 \
--cpus_per_task=1 \
--mem_per_cpu=2000 \
--walltime=01:00:00
```
I still need to test with the Vast
## Things I wasn't sure about
Tests - what is the best way to test uploads to s3? Presumably we would mock a request and not actually hit a real endpoint. The way AWS tests the `CRTTransferManager` is shown [here](https://github.com/boto/s3transfer/blob/7a0d98013197d02077c0ba71bbcd5f31d971a313/tests/functional/test_crt.py#L58)

Upload retries - I keep a list of filepaths that failed to upload, so those could be retried either within each worker or at the end in a serial pass. We could also run a `aws s3 sync` command at the end.

Code organization - is `/scripts` the best place to put the cluster submission code? It is general enough that it could potentially go in a separate repo

### CODE REVIEW

**Comment by jtyoung84** [comment]
I think it might be better to merge this branch into main if it's ready. It might be better to open another pull request for the tests and separating out the `scripts` if wanted.

**Review by jtyoung84 — APPROVED** [review]
I don't see anything immediately glaring if it's meeting the performance requirements. We can open issues/pr's to update the unit tests and reset the github actions.

**Review by sharmishtaa — APPROVED** [review]
I dont' see anything glaring at me either. Looks good to start with.

**Comment by carshadi** [comment]
got the go-ahead from @dyf , merging

**Pull request merged**
